### ISSUE TITLE
Cannot select v1.0.4 on bitrise

### ISSUE THREAD

**Issue by YukiOya** [ned1988/bitrise-step-git-tag-project-version-and-build-number#11]
Hi! Thank you for your step!

We want to use latest version(v1.0.4), but can't.

When can I use it? I hope to use latest version soon.

**Comment by denys-meloshyn** [comment]
Hi @YukiOya! Unfortunately it is still in [review](https://github.com/bitrise-io/bitrise-steplib/pull/2206). But you can check this [answer](https://github.com/bitrise-io/bitrise-steplib/pull/2206#issuecomment-547377175).
Hope it will help you and thanks for using this step 🙂

**Comment by YukiOya** [comment]
Oh, I didn't know that links, and hope the review will be passed.
Thanks.
