### ISSUE TITLE
Fails to extract build version

### ISSUE THREAD

**Issue by lucaskuzma** [ned1988/bitrise-step-git-tag-project-version-and-build-number#12]
Not sure if this is because I'm using a workspace (passed the _project_ path to the script), but it seems the build number is not being extracted correctly.

I see the following result:
`New tag: v2.8.8($(CURRENT_PROJECT_VERSION))
`

**Comment by denys-meloshyn** [comment]
Hi @lucaskuzma! If you are using `Xcode 11` you should put path to `xcodeproj`, because Apple moved the app version value from `plist` to `xcodeproj` property `MARKETING_VERSION`.
It seems like you have custom property in your project `CURRENT_PROJECT_VERSION` my script expect that in `CFBundleVersion` you will have actual value.

**Comment by lucaskuzma** [comment]
Yes, I pass the project path. And it looks like MARKETING_VERSION is extracted correctly.

But in my project, the version is stored like this:
`CURRENT_PROJECT_VERSION = 145;`

For example:

```
			buildSettings = {
				ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;
				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
				CLANG_WARN_COMMA = NO;
				CODE_SIGN_IDENTITY = "iPhone Developer";
				CODE_SIGN_STYLE = Manual;
				CURRENT_PROJECT_VERSION = 144;
```

So maybe this is a new Xcode setup? I don't think I have anything custom here.

Similar to MARKETING_VERSION, I can extract it like this:

```
CURRENT_PROJECT_VERSION=""
LINES=$(sed -n '/CURRENT_PROJECT_VERSION/=' "$PROJECT_PATH/project.pbxproj")
for LINE in $LINES; do
  CURRENT_PROJECT_VERSION=$(sed -n "$LINE"p "$PROJECT_PATH"/project.pbxproj)
  CURRENT_PROJECT_VERSION="${CURRENT_PROJECT_VERSION#*= }"
  CURRENT_PROJECT_VERSION="${CURRENT_PROJECT_VERSION%;}"
done
```

**Comment by denys-meloshyn** [comment]
@lucaskuzma yes you are right, seems like it was also changed. If I change it manually my value in `Info.plist` looks like this `<key>CFBundleVersion</key><string>$(CURRENT_PROJECT_VERSION)</string>`. Can I ask you how you bump the build number, using the `Set Xcode Project Build Number` step in `bitrise`?

**Comment by lucaskuzma** [comment]
We bump it manually using the Xcode UI, not with a build step.

**Comment by denys-meloshyn** [comment]
Yeah, in this case I need to prepare another release 😀

**Comment by denys-meloshyn** [comment]
@lucaskuzma created new [PR 1.0.5](https://github.com/bitrise-io/bitrise-steplib/pull/2326)

**Comment by denys-meloshyn** [comment]
@lucaskuzma PR merged
