### ISSUE TITLE
Result format doesn't propogate to tag 

### ISSUE THREAD

**Issue by njajones** [ned1988/bitrise-step-git-tag-project-version-and-build-number#15]
Tag defaults to v_VERSION_(_BUILD_) regardless of the format entered into Result format  field

**Comment by denys-meloshyn** [comment]
@njajones hi, can you please provide more data? 🙂

**Comment by njajones** [comment]
@denys-meloshyn I added a custom string to the Result Format field, e.g. foo_BUILD_, but the step git tagged v_VERSION_(_BUILD_)

**Comment by denys-meloshyn** [comment]
Can you please also tell what is the step version and can you provide your format?

**Comment by njajones** [comment]
1.0.6
and it was of the form `foo-_BUILD_` but I did try other variations (e.g. without the dash).

**Comment by denys-meloshyn** [comment]
Ok, seems like I know why its happening. I have next check:
```
  if [[ $bitrise_tag_format == *"_VERSION_"* ]]; then
    name="${bitrise_tag_format//_VERSION_/$CFBundleShortVersionString}"
    name="${name//_BUILD_/$CFBundleVersion}"
    printf -v TAG_NAME "$name"
  else
    # Support previous integration
    printf -v TAG_NAME "v%s(%s)" "$CFBundleShortVersionString" "$CFBundleVersion"
  fi
```

If I can't find `_VERSION_` I think that you are using an `old` format style.

**Comment by Kamillpg** [comment]
I also have that problem. I'm using 1.0.7 version and I want to skip the VERSION in the tag. (I'm only interested in build number.) My format: Build_BUILD_, but it appears as the default format. Could you provide some way to skip the version number?

**Comment by denys-meloshyn** [comment]
@Kamillpg @njajones in new version `1.0.9` it should be possible now
https://github.com/bitrise-io/bitrise-steplib/pull/2511
