### ISSUE TITLE
Creating wrong tag name

### ISSUE THREAD

**Issue by renatosmf** [ned1988/bitrise-step-git-tag-project-version-and-build-number#28]
Scenery:

- Run the workflow `bitrise-step-git-tag-project-version-and-build-number` over a project with the current version starting with number `1`. e.g. (11.x.x, 12.x.x)

Problem:

The workflow will create a tag name with the wrong value. e.g ("v1.0(1)").

**Comment by gabrielmoraees** [comment]
@renatosmf do you know if there's a workaround for this issue? I'm also facing it

**Comment by denys-meloshyn** [comment]
Hi @gabrielmoraees, which step version are you using and can you tell how you set project version in Xcode?
