### ISSUE TITLE
Xcode11 uses MARKETING_VERSION variable

### ISSUE THREAD

**Issue by CedricSoubrie** [ned1988/bitrise-step-git-tag-project-version-and-build-number#6]
Xcode 11 changed the way the version is stored in the project :

1. when changing the `Version` text field of the project, Xcode now create a MARKETING_VERSION  variable. 
2. `Bundle versions string, short` in info.plist now has the default value $MARKETING_VERSION.

When using _version_ in bitrise step we get "$MARKETING_VERSION" string and not the "1.6" string.

**Comment by denys-meloshyn** [comment]
Huge thanks @CedricSoubrie for heads up, will try to release new version ASAP

**Comment by denys-meloshyn** [comment]
@CedricSoubrie submitted PR with fix for review

**Comment by CedricSoubrie** [comment]
👍 Nice @ned1988 !  I'll try it on wednesday when I'll be working on a project using bitrise.
